### PR TITLE
Header changed 

### PR DESCRIPTION
**Pull request by aarav0180**
Added a constant margin to header as auto margin was giving issues in some browsers.

### CODE REVIEW

**Comment by LWinterberg** [comment]
`margin: auto` has been well supported everywhere for well over a decade. What browser causes the issue?

**Comment by aarav0180** [comment]
Screenshot 2024-08-26 160121
Screenshot 2024-08-26 160236

In brave Browser the side margin of nav bar is very less so it's better to keep it a constant so that it can be even in all the browsers .

**Comment by aarav0180** [comment]
And not only the header it's almost with whole body there's no margin from the sides .

Screenshot 2024-08-26 160706

**Comment by LWinterberg** [comment]
Looks like we have a sourspot for padding for widths == 1280. All resolutions above and below have appropriate paddings.

**Comment by aarav0180** [comment]
yep, It can happen as tailwind CSS uses predefined breakpoints for different screen sizes. 

So, can I look up on that issue ? It can be solved by doing some simple changes.

**Comment by aarav0180** [comment]
And btw it only occurs in brave browser as in my edge it's working fine but the brave site shows the issue .
Screenshot 2024-08-26 180639

**Pull request closed without merging**
